# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Versions
          command: npm -v && node -v

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i
      - run:
        command: |
          echo Running test


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Code Lint
          command: npm run lint

      - run:
          name: Red
          command:
            npm run test:red &&
            npm run build:red

      - run:
          name: Blue
          command:
            npm run test:blue &&
            npm run build:blue

      - run:
          name: Green
          command:
            npm run test:green &&
            npm run build:green
